### ISSUE TITLE
error in decoder

### ISSUE THREAD

**Issue by sbanerj2** [HyeongseokSon1/deep_blur_detection_and_classification#3]
I am getting the following error when using the main.py code:
Tensorflow version: tensorflow-gpu            1.14.0
Tensorlayer version : tensorlayer               1.8.2
I am using a virtual conda environment. Seems like no version of tensorflow 1.13 is not available .
Previously was using the latest stable version of tensorlayer with tensorflow-gpu==2.0.0-beta1, however, tensorflow2.0 doesn't have the support for tf.placeholder and was getting struck. Any help would be appreciated.
``
The TensorFlow contrib module will not be included in TensorFlow 2.0.                                                   For more information, please see:                                                                                         * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md                                   * https://github.com/tensorflow/addons                                                                                  * https://github.com/tensorflow/io (for I/O related ops)                                                              If you depend on functionality not listed there, please file an issue.                                                                                                                                                                          Traceback (most recent call last):                                                                                        File "main.py", line 148, in <module>                                                                                     blurmap_3classes(args.index) # test_code                                                                              File "main.py", line 91, in blurmap_3classes                                                                              output,m1,m2,m3= Decoder_Network_classification(n, f0, f0_1, f1_2, f2_3 ,hrg,wrg, reuse = reuse, scope = scope1)      File "/home/sbanerjee/blur_detection/deep_blur_detection_Kim2018-master/model.py", line 340, in Decoder_Network_classification                                                                                                                    n = DeConv2d(n, 512, (3, 3), (hrg / 8, wrg / 8), (2, 2), act=None, padding='SAME', W_init=w_init4,                    File "/home/sbanerjee/anaconda3/envs/SV-blur/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 532, in __truediv__                                                                                                   "please use // instead".format(type(other).__name__))                                                               TypeError: unsupported operand type(s) for /: 'Dimension' and 'int', please use // instead 
``

**Comment by PhenomenalOnee** [comment]
replace '/' with '//' in DeConv2d layer, so
DeConv2d(n, 512, (3, 3), (hrg / 8, wrg / 8), (2, 2), act=None, padding='SAME', W_init=w_init4
becomes
DeConv2d(n, 512, (3, 3), (hrg // 8, wrg // 8), (2, 2), act=None, padding='SAME', W_init=w_init4
