### ISSUE TITLE
데이터셋 요청하고 싶습니다. 

### ISSUE THREAD

**Issue by moonchildz** [HyeongseokSon1/deep_blur_detection_and_classification#8]
안녕하세요. 이 git 및 연결된 논문에 관한 추가적인 연구를 하고 싶습니다. 

혹시 논문 안에서 언급한 데이터셋을 받을 수 있는 방법이 있을까요 ?

**Comment by HyeongseokSon1** [comment]
어떤 데이터셋을 말하시는 건가요?
Blur detection dataset은 CUHK dataset을 그대로 사용했고
Synthetic dataset은 readme에 있는 google drive 링크에서 받으실 수 있습니다.

**Comment by moonchildz** [comment]
앗 아닙니다 제가 아래에 있는 링크를 발견 못했었군요 
감사합니다. 잘 활용하겠습니다.
